function HW_11_Rect_GradientPlot(dist, stresses, fit1,fit2,fit3)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data
%  X2:  vector of plot x data
%  YMATRIX2:  matrix of plot y data

%  Auto-generated by MATLAB on 16-Apr-2023 15:26:00

% Create figure
figure1 = figure('NumberTitle','off','Name','Figure','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(dist,stresses,'Marker','x','LineStyle','none');
set(plot1(1),'DisplayName','216 elements');
set(plot1(2),'DisplayName','21600 elements');
set(plot1(3),'DisplayName','2160000 elements',...
    'Color',[0.494117647058824 0.184313725490196 0.556862745098039]);

% Create multiple line objects using matrix input to plot
plot2 = plot(fit1);
plot3 = plot(fit2);
plot4 = plot(fit3);

set(plot2,'DisplayName','216 elements curve fit',...
    'Color',[0.0745098039215686 0.623529411764706 1]);
set(plot3,'DisplayName','21600 elements curve fit',...
    'Color',[1 0.411764705882353 0.16078431372549]);
set(plot4,'DisplayName','2160000 elements curve fit',...
    'Color',[0.717647058823529 0.274509803921569 1]);

% plot2 = plot(X2,YMatrix2);
% plot3 = plot(fit2);
% plot4 = plot(fit2);
% 
% set(plot2(1),'DisplayName','216 elements curve fit',...
%     'Color',[0.0745098039215686 0.623529411764706 1]);
% set(plot2(2),'DisplayName','21600 elements curve fit',...
%     'Color',[1 0.411764705882353 0.16078431372549]);
% set(plot2(3),'DisplayName','2160000 elements curve fit',...
%     'Color',[0.717647058823529 0.274509803921569 1]);


% Create ylabel
ylabel('Max Principal Stress, psi');

% Create xlabel
xlabel({'x Distance from Boundry Consdition, in',''});

% Create title
title({'Square Elements Stress Gradient in x Direction',''});

box(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','best');

