function [x_2_r, y_2_r, x_f_2_r, y_f_2_r, M_s, lambda_s, M_f, lambda_f] = importAxisymmetricSpike(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  [XR, YR, M_S, LAMBDA_S, M_F, LAMBDA_S1] = IMPORTFILE(FILE) reads data
%  from the first worksheet in the Microsoft Excel spreadsheet file
%  named FILE.  Returns the data as column vectors.
%  desinged to take tables from conors, mayers paper
%
%  [XR, YR, M_S, LAMBDA_S, M_F, LAMBDA_S1] = IMPORTFILE(FILE, SHEET)
%  reads from the specified worksheet.
%
%  [XR, YR, M_S, LAMBDA_S, M_F, LAMBDA_S1] = IMPORTFILE(FILE, SHEET,
%  DATALINES) reads from the specified worksheet for the specified row
%  interval(s). Specify DATALINES as a positive scalar integer or a
%  N-by-2 array of positive scalar integers for dis-contiguous row
%  intervals.
%
%  Example:
%  [xr, yr, M_s, lambda_s, M_f, lambda_s1] = importfile("C:\Users\j433p144\OneDrive - University of Kansas\MATLAB\Autumn 2024\Missile Design Continued\Propulsion\Axisymmetric_Isentroipc_Spike_M2.xlsx", "Sheet1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Oct-2024 14:01:03

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["xr", "yr", "M_s", "lambda_s", "M_f", "lambda_f"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Import the data
tbl = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    tbl = [tbl; tb]; %#ok<AGROW>
end

%% Convert to output type
x_2_r = tbl.xr;
y_2_r = tbl.yr;
M_s = tbl.M_s;
lambda_s = tbl.lambda_s;
M_f = tbl.M_f;
lambda_f = tbl.lambda_f;

% store the focal point seperately
x_f_2_r = x_2_r(end);
y_f_2_r = y_2_r(end);

x_2_r = x_2_r(1:end-1);
y_2_r = y_2_r(1:end-1);
M_s = M_s(1:end-1);
lambda_s = lambda_s(1:end-1);
M_f = M_f(1:end-1);
lambda_f = lambda_f(1:end-1);

end