function MinPrincipalGradient(X1, YMatrix1)
%MinPrincipalGradient(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 07-May-2023 15:10:21

% Create figure
figure1 = figure('NumberTitle','off','Name','Figure','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'DisplayName','fine','Marker','x','LineStyle','none');
set(plot1(2),'DisplayName','medium','Marker','x','LineStyle','none',...
    'Color',[1 0.0745098039215686 0.650980392156863]);
set(plot1(3),'DisplayName','coarse','Marker','x','LineStyle','none',...
    'Color',[0.392156862745098 0.831372549019608 0.0745098039215686]);
set(plot1(4),'DisplayName','fine curve fit',...
    'Color',[0 0.447058823529412 0.741176470588235]);
set(plot1(5),'DisplayName','medium curve fit',...
    'Color',[1 0.0745098039215686 0.650980392156863]);
set(plot1(6),'DisplayName','coarse curve fit',...
    'Color',[0.392156862745098 0.831372549019608 0.0745098039215686]);

% Create ylabel
ylabel('Min Principal Stress, psi');

% Create xlabel
xlabel('Distance From Boundrary Condition, inches');

% Create title
title('Min Principal Gradient');

box(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'NumColumns',2,'Location','best');

