function plotSingalVTime(time, Singals,dataName)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 24-Apr-2023 13:15:09

% Create figure
figure1 = figure('Name','Figure','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(time,Singals);
set(plot1(1),'DisplayName',dataName);
set(plot1(2),'DisplayName','$sin(3t/7)$');

% Create ylabel
ylabel('Amplitude');

% Create xlabel
xlabel('Time');

% Create title
title('Signal vs. Time');

box(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex');

