classdef ThermodynamicState
    %ThermodynamicState Represents a state of a thermodynamic system.
    %   Relates the properties of a thermodynamic system such as pressure
    %   temperature and volume and creates relations to assoiciate them.

    properties
        stateName % this will be used behind the scenes to distinguish this state from others

        % the previous and next device arguments allow this to act as a
        % relation thus turning a jet engine into a relational structure
        % the mass flow rate fraction allows multiple edge to come out of a
        % given node
        previousDevice % this is a device object that will be outputing to this state (note only one may exist use splitter devices if required)
        nextDevice % this is a device object that will be inputing from this state (note only one may exist use splitter devices if required)
        massFlowRateFraction % this represent what fraction of the mass flow rate out of the previous device (node) this state (edge) constains (string)
        
        asumpts % this will define which relations to use to relate the thermodynamic properties (could maybe just use "gas law" and then maxwell relations)
        
        relations % thses will be the relations generated by the state

        thermoProperties % these are all of the thermodynamic poperties of the device

        hasPreviousDevice % identifies if provided with a previous device
        hasNextDevice % identifies if provided with a next device

    end

    methods
        function self = ThermodynamicState(stateName, asumpts, options)
            %ThermodynamicState Construct an instance of this class
            %   define input and output devices inorder to use as edge
            %   in a graph does not need to be done

            arguments
                stateName string
                asumpts (1,:) string % TODO add validator that it is one of the valid assumption options see style example in documentation of optional args
                options.previousDevice % TODO: add validator that it is a thermodynamic device or nan
                options.nextDevice % TODO: add validator that it is a thermodynamic device or nan
                options.massFlowRateFraction = "1" % the fraction of mass flow rate which come from the previous device into this device (for use with splitters) delauts to 1 (i.e. assumes unsplit flow)
            end

            self.stateName = stateName;
            self.asumpts = asumpts;

            self.massFlowRateFraction = options.massFlowRateFraction;

            %if provided with previous en next devises assignm them
            if isfield(options,"previousDevice") %may be better to implement previous and next devices as positional arguments with defalut values
                self.previousDevice = options.previousDevice;
                self.hasPreviousDevice = true;
            else
                self.hasPreviousDevice = false;
            end
            if isfield(options,"nextDevice")
                self.previousDevice = options.nextDevice;
                self.nextDevice = true;
            else
                self.hasNextDevice = false;
            end

            %% this code actualy does the generation of relations
            % note the above double % may cause issues I am unsure

            suffix = sprintf("_%s",stateName); % all relations will use _stateName to identify the variables which are related to them

            if self.hasPreviousDevice
                prevDevSuff = "_" + self.previousDevice.name() + "out";
            end
            if self.hasNextDevice
                nextDevSuff = "_" + self.nextDevice.name(); % this bit of code is unnesseary
            end
            
            % define a list of all properties that can be define at any thermodynamic state
            properties = [... % may need to rename this to avoid conflict with keyword
                "p"; "T"; "nu"; "rho"; % pressure; temperature; specific volume; density;
                "u"; "h"; "s";  % internal energy; enthalpy; entropy;
                "mdot"; "V"; "A"; % mass flow rate; velocity; cross sectional area;
                "M"; "a"; % Mach Number; Speed of sound
                "Pt"; "Tt"; "ht"; "rhot"; % total pressure; total temperature; total enthalpy; total density
                "gamma"; "cp"; "cv"; % ratio of specific heats; constant pressure specific heat; constant volume specific heat. Note: cp cv gamma are not chaging at a state they only change in a device
                "R"; % gas specific constant 
                ];

            self.thermoProperties = arrayfun(@(property) property + suffix, properties); % create a specific version of properties for this object
            
            equations = []; % this is the array that hold all the equations we will later turn into relations
            % TODO: ensure that equations is oriented in the aproprate direction i.e. horizontal/verticle

            if self.hasPreviousDevice
                prevDevProps = arrayfun(@(property) property + prevDevSuff, properties); % create the properties names from the prevous device
                % set all properties excpet for mass flow rate equal to the output properties from the previous device.
                % mass flow rate will be ralated via the mass flow rate fration

                % relate all properties excpet for mdot
                mdotFilter = properties ~= "mdot" % an array of logical values tha is true unless the element is mdot
                equatorTempate = sprintf("x_%s = x_%s",suffix,prevDevSuff); % create a template for property relating equations
                equations = [equations; equationRepeater([equatorTempate] , "x", properties(mdotFilter)')']; % add an equation relating the output of the previous device to this thermodynamic state

                % relate mdots
                equations(end+1) = sprintf("mdot_%s = %s * mdot_%s", suffix, self.massFlowRateFraction, prevDevSuff);
            end

            


            gasLaw = "p_x * nu_x = R_x * T_x"; % for now (MVP) only use the ideal gas law
            % TODO: implement maxwell relations to relate pressure temperature and volume to internal energy enthalpy and entropy

            %TODO: fugacity and gibbs and helmholtz

            rawEqs = [...
                %add relations amongst properties that are true (always)
                "h_x = u_x + p_x * v_x";
                "gamma_x = cp_x / cv_x";
                "mdot_x = rho_x * A_x * V_x";

                %for now ideal gas law gives us
                "p_x * nu_x = R_x * T_x"
                "cp_x = cv_x + R_x";

                %with constant specifc heats we get
                "cp_x = gamma_x / (gamma_x - 1) * R_x";
                "cv_x = 1 / (gamma_x - 1) * R_x";

                %mach number
                "a_x = (gamma_x*R_x*T_x)^.5";
                "M_x = V_x / a_x";
                "p_x = rho_x*a_x^2/gamma_x";
                "mdot_x = p_x*gamma_x*A_x*M_x/a_x";
                "mdot_x = (gamma_x/R_x)^.5 * p_x / (T_x)^.5 * A_x * M_x";
                "mdot_x = (gamma_x/R_x)^.5 * pt_x / (Tt_x)^.5 * A_x * M_x * (1 / (1 + (gamma_x-1)/2*M^2) )^((gamma_x+1)/(2*(gamma_x-1)))";

                %TODO: implent sonic condition euquations see faroqui page 64,65

                %from isentropic relations
                "ht_x = h_x + V_x^2 / 2";

                "Tt_x = T + V^2 / (2*c_p)" % caloricly perfect
                "Tt_x/T_x = 1 + (gamma_x-1)/2 * V_x^2/a_x^2"; % caloricly perfect
                "Tt_x/T_x = 1 + (gamma_x-1)/2 * M_x^2"; % caloricly perfect

                "pt_x/p_x = (Tt_x/T_x)^(gamma_x/(gamma_x-1))"; % caloricly perfect
                "pt_x/p_x = (1 + (gamma_x-1)/2 * M_x^2)^(gamma_x/(gamma_x-1))"; % caloricly perfect

                "rhot_x/rho_x = (pt_x/p_x)^(1/gamma_x)"; % caloricly perfect
                "rhot_x/rho_x = (1 + (gamma_x-1)/2 * M_x^2)^(1/(gamma_x-1))"; % caloricly perfect
                ];
            equations = [equations; equationRepeater(rawEqs,"x",suffix)'];

            %make assumptions for the equations
            Assumpts = dictionary();
            Assumpts(sprintf("M_%s",suffix)) = {["positive","real"]}; % Mach Number is positive and real
            Assumpts(sprintf("p_%s",suffix)) = {["positive","real"]}; % Pressure must be positive
            Assumpts(sprintf("pt_%s",suffix)) = {["positive","real"]}; % Total Pressure must be positive
            Assumpts(sprintf("T_%s",suffix)) = {["positive","real"]}; % Temperature must be positive
            Assumpts(sprintf("Tt_%s",suffix)) = {["positive","real"]}; % Temperature must be positive
            Assumpts(sprintf("a_%s",suffix)) = {["positive","real"]}; % Speed of Sound must be positive
            Assumpts(sprintf("rho_%s",suffix)) = {["positive","real"]}; % density must be positive
            Assumpts(sprintf("rhot_%s",suffix)) = {["positive","real"]}; % total density must be positive
            Assumpts(sprintf("nu_%s",suffix)) = {["positive","real"]}; % specific volume must be positive
            Assumpts(sprintf("V_%s",suffix)) = {["positive","real"]}; % velocity must be positive
            Assumpts(sprintf("mdot_%s",suffix)) = {["positive","real"]}; % mass flow rate must be positive
            Assumpts(sprintf("R_%s",suffix)) = {["positive","real"]}; % gas cosntant must be positive
            Assumpts(sprintf("gamma_%s",suffix)) = {["positive","real"]}; % ratio of specific heats must be positive
            Assumpts(sprintf("cp_%s",suffix)) = {["positive","real"]}; % constnat pressure specific heat must be positive
            Assumpts(sprintf("cv_%s",suffix)) = {["positive","real"]}; % constnat pressure specific heat must be positive
            Assumpts(sprintf("A_%s",suffix)) = {["positive","real"]}; % cross sectional area must be positive

            % create relation objects

            assumpVars = Assumpts.keys; % prepare assumptions

            self.relations = Relation.empty([0,length(equations)]); % declare list of relations
            for i = 1:length(equations) % populate list of relations
                equation = equations(i);

                %check to see if any of the terms of the equation require an assumption
                %to be made on them

                eqAssumpts = dictionary(); % prepare an assumptions dictionary to store relevant assumptions

                % tokenize the expression
                vars = string(symvar(str2sym(equation)));

                % check each variable for an assumptions match
                for var = vars
                    % for now we we want all our values to be real so add that assumption
                    eqAssumpts(var) = {["real"]};
                    if strcmp(var,assumpVars)% if the expression matches a assumption var add it to the assumptions
                        eqAssumpts(var) = Assumpts(var);
                    end
                end

                %create the relation
                if eqAssumpts.isConfigured %if there are assumptions to make
                    self.relations(i) = Relation(equations(i),"variableAssumptions",eqAssumpts); %create the relation with the assumption
                else %otherwize there are no assumtions to make
                    self.relations(i) = Relation(equations(i)); % it may be acceptable to pass an empty dictionary instead of this if statement
                end

            end
        end

        % should i have a function to try to solve all of this objects relations?
    end
end