classdef ThermodynamicDevice < handle
    %ThermodynamicDevice a device which changes thermodynamic states which
    %pass into/outof it
    %   steady state is implicity assumed

    properties
        name % name of device (string)

        gasLaw % gas law object used by the device to clculate properties

        inputStates % states which feed into the device (thermodynamicState)
        outputStates % states which flow out of the device (thermodynamicState)

        massFlowRateFractions % fractions of mass flow rate that go out to each device

        worksIn % work done on the device (string)
        worksOut % work done by the device (string)

        heatTransfersIn % heat transfer to the device (string)
        heatTransfersOut % heat transfer from the device (string)

        asumpts % this will define which relations to use to relate the thermodynamic properties (could maybe just use "gas law" and then maxwell relations)
        
        relations % thses will be the relations generated by the state

        outThermoProperties % these are all of the thermodynamic poperties of the device
        parameters % parameters that relat the input states to the output states

        primaryInlet % this defines which is the primaty inlet for example air and fuell both flow into combustion chamber but the pi,tau, and e  terms relate the air inlet to the outlet
    end

    methods
        function self = ThermodynamicDevice(name, gasLaw, assumpts)
            %ThermodynamicDevice Construct an instance of thermodynamic
            %Device
            %   Detailed explanation goes here
            
            %TODO: implement the class
            self.name = name;
            self.asumpts = assumpts;
            self.gasLaw = gasLaw;

            self.massFlowRateFractions = dictionary();
            % TODO: add optional args for edges on creation that 

            disp("currently only works for one input one output systems");
        end

        function addStateEdgeIn(self,inputState)
            self.inputStates = [self.inputStates inputState];
        end

        function addStateEdgeOut(self, outputState, massFlowRateFraction)
            arguments
                self
                outputState
                massFlowRateFraction string
            end
            % set mass flow rate fraction = 1 for a single output device
            self.outputStates = [self.outputStates outputState];
            self.massFlowRateFractions(outputState.stateName) = massFlowRateFraction;
            
        end

        % TODO: add "add work edge in" method
        % TODO: add "add heat transfer in" method
        % TODO: add "add state edge out" method
        % TODO: add "add work edge out" method
        % TODO: add "add heat transfer out" method
        % TODO: add "set efficincies" method % maybe not needed 
        % TODO: add "generate relations" method

        % TODO: add "remove state,work, heat transfer..." methods

        function generateReltions(self,inputArg)
            %generateReltions generates relations from this object
            %   Please try to avoid calling this unless you have full
            %   configured you input and output states as adding/ removing
            %   them will 

            relations = []; % this is just here so that my ide stops yelling at me. remove when implemented

            equations = [];

            %% cons mass
            consMassEq = sprintf("mdot_%s_out = 0",self.name); % default to no mass flow
            totalMassFlow = 
            massFractionEquations = [""]
            massFractionEquation = foo; % not yet implemented

            for state = self.inputStates()
                consMassEq = sprintf("%s + mdot_%s",consMassEq,state.stateName); % add the mass flow of a given input state
                massFractionEquations = [massFractionEquations, sprintf("Y_%1$s_%2$s mdot_%1$s/mdot_%2$s_out",state.stateName,self.name)];
            end

            %TODO check sum of mass fractions out = 1

            for state = self.inputStates()
                massFractionEquations(end+1) = sprintf("%s + mdot_%s",consMassEq,state.stateName); % compute mass fraction
            end

            


            equations = [equations; consMassEq];

            %% cons energy
            consEnergyEq = sprintf("mdot_%1$s_out * (h_%1$s + V_%1$s^2/2) = 0",self.name);

            for state = self.inputStates()
                consEnergyEq = sprintf("%1$s + mdot_%2$s * (h_%2$s + V_%2$s^2/2)",consEnergyEq,state.stateName); % add the mass flow of a given input state
            end

            for work = [self.worksIn]
                consEnergyEq = sprintf("%1$s + %2$s )",consEnergyEq,work); % add the work in
            end

            for work = [self.worksOut]
                consEnergyEq = sprintf("%1$s - %2$s )",consEnergyEq,work); % subract the work out
            end

            for heatTransfer = [self.heatTransfersIn]
                consEnergyEq = sprintf("%1$s + %2$s )",consEnergyEq,heatTransfer); % add the heat transfer in
            end

            for heatTransfer = [self.heatTransfersOut]
                consEnergyEq = sprintf("%1$s - %2$s )",consEnergyEq,heatTransfer); % subract the heat transfer out
            end

            % TODO: the above was the governing form of the conservstion of
            % energy we are constrained by the gas law implement here
            enthalpy_out_specific = string(subs(self.gasLaw.formulas.Delta.HrTP,[T,v,p],[sprintf("T_%s_out",self.name),sprintf("v_%s_out",self.name),sprintf("p_%s_out",self.name)]))

            enthalpy_in_specific = "" %weighted sum in
            %then use the gas law to relate the two and get delta h total?
            %why would i do that?



            equations = [equations; consEnergyEq];

            %conservation of mass
            %mass of inputs
            %mass of out State (mass of individual thermo states will be worked out by the state itself)


            self.realtions = relations;
        end
    end
end